version: "3"

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
  php:
    image: php:8.2-apache
    container_name: php
    build: php
    ports:
      - 8080:80
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
volumes:
  db:
  php:
