version: "3"

services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test01
      POSTGRES_PASSWORD: test01
      POSTGRES_DB: test01
  php:
    image: php:8.2-apache
    container_name: php
    build: php
    ports:
      - 8080:80
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
volumes:
  db:
  php:
